import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'blocks', title: 'Blocks'},
    {name: 'meta', title: 'Meta'},
  ],
  fields: [
    defineField({
      name: 'portfolio',
      title: 'Portfolio',
      type: 'string',
      options: {list: ['systems', 'graphics'], layout: 'radio'},
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      description: 'Used as ?id= in project-template.html — keep it matching the old project id if migrating.',
      options: {source: 'title'},
      validation: (Rule) => Rule.required(),
      group: 'content',
    }),
    defineField({name: 'latin', title: 'Subtitle / latin name', type: 'string', group: 'content'}),
    defineField({name: 'cat', title: 'Category line', type: 'string', group: 'content'}),
    defineField({name: 'year', title: 'Year', type: 'string', group: 'content'}),
    defineField({name: 'hero', title: 'Hero media', type: 'media', group: 'content'}),
    defineField({name: 'desc', title: 'Description', type: 'text', group: 'content'}),
    defineField({name: 'shortDesc', title: 'Short description (card)', type: 'string', group: 'content'}),
    defineField({name: 'role', title: 'Role', type: 'string', group: 'content'}),
    defineField({
      name: 'tools',
      title: 'Tools',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
      group: 'content',
    }),
    defineField({
      name: 'tags',
      title: 'Tags (card chips)',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
      group: 'content',
    }),
    defineField({
      name: 'externalLink',
      title: 'External link',
      type: 'url',
      description: 'Only for projects still hosted elsewhere. Leave blank to use project-template.html?id=slug.',
      group: 'content',
    }),
    defineField({
      name: 'blocks',
      title: 'Content blocks',
      type: 'array',
      of: [
        {type: 'textBlock'},
        {type: 'imageBlock'},
        {type: 'imagePairBlock'},
        {type: 'videoBlock'},
        {type: 'pullquoteBlock'},
        {type: 'statsBlock'},
        {type: 'dividerBlock'},
      ],
      group: 'blocks',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {list: ['active', 'archived', 'thesis']},
      description: 'Drives the coloured status dot — graphics projects only.',
      group: 'meta',
    }),
    defineField({name: 'statusLabel', title: 'Status label', type: 'string', group: 'meta'}),
    defineField({name: 'visible', title: 'Visible on site', type: 'boolean', initialValue: true, group: 'meta'}),
    defineField({name: 'featuredHome', title: 'Show on homepage', type: 'boolean', initialValue: false, group: 'meta'}),
    defineField({
      name: 'isFeatured',
      title: 'Is the section spotlight',
      type: 'boolean',
      initialValue: false,
      description: 'Marks this as systems.featured / graphics.featured — only one per portfolio should be true.',
      group: 'meta',
    }),
    defineField({
      name: 'badge',
      title: 'Badge (spotlight only)',
      type: 'string',
      description: 'e.g. "Thesis · UAL 2025 · Distinction" — only shown when Is the section spotlight is on.',
      hidden: ({document}) => !document?.isFeatured,
      group: 'meta',
    }),
  ],
  preview: {
    select: {title: 'title', subtitle: 'cat', media: 'hero.image', portfolio: 'portfolio'},
    prepare({title, subtitle, media, portfolio}) {
      return {title, subtitle: `${portfolio ?? ''} — ${subtitle ?? ''}`, media}
    },
  },
})
